#!/usr/bin/env python3
# ===========================================================
#  AI Talent Engine – Enterprise Suite Builder
#  © 2025 L. David Mendoza – All Rights Reserved
# ===========================================================
import os, subprocess, datetime, json, hashlib, sys, platform

BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOGS = os.path.join(BASE, "logs")
os.makedirs(LOGS, exist_ok=True)
REPORT = os.path.join(LOGS, f"enterprise_build_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.log")

def log(msg):
    ts = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    print(msg)
    with open(REPORT, "a") as f:
        f.write(f"{ts} {msg}\n")

log("🚀 Starting AI Talent Engine Enterprise Suite Build...")

# --- 1️⃣ Dependency Check ---
log("🔍 Checking and installing dependencies...")
subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "streamlit", "plotly", "reportlab", "networkx"], check=False)

# --- 2️⃣ Core Structure ---
dirs = ["core", "demos/agents", "demos/config", "demos/narration", "output", "logs", "archive"]
for d in dirs:
    os.makedirs(os.path.join(BASE, d), exist_ok=True)
    log(f"📂 Ensured directory: {d}")

# --- 3️⃣ Create Placeholder Files ---
core_modules = [
    "system_health.py", "security_audit.py", "contact_enrichment.py", "integrity_verifier.py",
    "snapshot_backup.py", "dashboard_connector.py", "start_dashboard.sh", "voice_monitor.py",
    "demo_logger.py", "demo_trigger.py", "research_scheduler.py", "data_normalizer.py",
    "ranking_engine.py", "signal_vectorizer.py", "insight_exporter.py", "phase_initializer.py",
    "setup_integrity_hooks.py", "licensing_injector.py", "legal_manifest_generator.py",
    "final_verification.py", "deploy_to_github.py"
]
for module in core_modules:
    path = os.path.join(BASE, "core", module)
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(f"# {module}\n# Auto-generated by build_enterprise_suite.py\n# © 2025 L. David Mendoza – All Rights Reserved\n")
        log(f"🧱 Created: {module}")

# --- 4️⃣ Demo Narration Configs ---
demo_map = """demos:
  - agent: citation_velocity
    description: "Analyzes citation velocity and influence tiers."
  - agent: rlhf_alignment
    description: "Demonstrates RLHF fine-tuning pipeline visualization."
  - agent: vector_db_rag
    description: "Retrieval-Augmented Generation search demonstration."
  - agent: multimodal_agent
    description: "Combines text, image, and speech reasoning."
"""
with open(os.path.join(BASE, "demos/config/demo_map.yaml"), "w") as f:
    f.write(demo_map)
log("🗺️ Demo map created.")

# --- 5️⃣ Provenance Manifest ---
manifest = {"author": "L. David Mendoza", "timestamp": datetime.datetime.now().isoformat(), "files": []}
for root, _, files in os.walk(BASE):
    for file in files:
        path = os.path.join(root, file)
        if any(x in path for x in [".git", "__pycache__"]): continue
        with open(path, "rb") as f:
            manifest["files"].append({"path": path.replace(BASE + "/", ""), "sha256": hashlib.sha256(f.read()).hexdigest()})
with open(os.path.join(LOGS, "provenance_manifest.json"), "w") as f:
    json.dump(manifest, f, indent=2)
log("🧾 Provenance manifest generated.")

# --- 6️⃣ Verification Call ---
subprocess.run([sys.executable, "core/final_verification.py"], check=False)
log("🧠 Verification check executed.")

# --- 7️⃣ Git Commit & Push ---
subprocess.run(["git", "add", "."], check=False)
subprocess.run(["git", "commit", "-m", "Enterprise Suite Build — AI Talent Engine vFinal 2025"], check=False)
subprocess.run(["git", "push", "-u", "origin", "main"], check=False)
log("📤 Repository push completed.")

# --- 8️⃣ Final Summary ---
log("────────────────────────────────────────────")
log("🏁 ENTERPRISE SUITE BUILD COMPLETE")
log("📄 Log file: " + REPORT)
log("🌐 Dashboard: http://localhost:8501")
log("© 2025 L. David Mendoza – All Rights Reserved")
log("────────────────────────────────────────────")
