#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="/Users/davemendoza/Desktop/Research_First_Sourcer_Automation"
README_PATH="${REPO_ROOT}/README.md"
COMMIT_MSG="Enforce mandatory execution rules and explicit paste instructions"

echo "============================================================"
echo "AI Talent Engine — README Rules Enforcer"
echo "Run UTC: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "============================================================"

cd "${REPO_ROOT}"

echo "[1/4] INVENTORY CHECK"
test -d "${REPO_ROOT}" || { echo "ERROR: Repo root not found"; exit 2; }

echo "Top-level files:"
find . -maxdepth 1 -type f | sed 's|./||' | sort || true

mkdir -p scripts

echo
echo "Git status:"
git status -sb || { echo "ERROR: Git not available"; exit 2; }

echo
echo "[2/4] OVERWRITING README.md"

cat > "${README_PATH}" <<'MD'
# AI Talent Engine — Research First Sourcer Automation

© 2025 L. David Mendoza  
All rights reserved.

This repository contains the **AI Talent Engine**, a Python-based, research-grade talent intelligence system designed for daily operational use, audit safety, and interview-ready demonstrations.

This README is **not informational only**.  
It is a **mandatory execution contract** governing how all files, scripts, and workflows in this repository are created, delivered, and executed.

---

## 🔒 MANDATORY SETUP RULES — FILE CREATION & EXECUTION

These rules are **locked and enforced**. Violations are execution failures.

---

## 1️⃣ Mandatory Inventory Check (Always First)

Before any execution:
- Confirm which files exist
- Confirm which files do not exist
- Confirm what is complete vs pending

❌ No searching for files that don’t exist  
❌ No guessing paths  

---

## 2️⃣ Front-End, Best-in-Class Execution Only

Always deliver production-grade outputs immediately.

❌ No options  
❌ No recommendations after the fact  
❌ No follow-up “enhancements”  

---

## 3️⃣ Full File Replacement Only

You must always deliver:
- The entire file
- Fully revised
- Ready to save
- With headers, validation steps, and git commands

❌ No snippets  
❌ No partial edits  

---

## 4️⃣ Autogeneration Is Mandatory

Everything possible must be autogenerated:
- Files
- Values
- Calculations
- Metadata

Manual steps = failure.

---

## 5️⃣ Nano Is Forbidden

❌ Nano  
❌ Interactive editing  
❌ Incremental patching  

---

## 6️⃣ Explicit Paste & Execution Instructions (Mandatory)

Every delivery must explicitly state:
- **Where to paste** (terminal vs file)
- **Exact file path**
- **Exact execution command**

❌ Ambiguity is prohibited  
❌ Implicit assumptions are prohibited  

---

## 🧠 Execution Philosophy

- Python-only
- Public, compliant data only
- Provenance-first
- Schema and column order are frozen

---

## 🧩 Track Definitions

**Track A:** Deterministic export  
**Track B:** Rule-based inference only  
**Track C:** Public discovery with provenance  

---

## 📌 Enforcement

Any violation of this README invalidates the execution.

---

## ✅ Status

This README is active and enforced.
MD

echo "[3/4] COMMIT + PUSH"
git add README.md
git commit -m "${COMMIT_MSG}" || echo "No changes to commit"
git push

echo
echo "[4/4] DONE — README enforced"
echo "============================================================"
